#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
thirdparty_obj = []

thirdparty_dir = "#thirdparty/mimalloc/"
thirdparty_sources = thirdparty_dir + "src/static.c"

env_thirdparty = env.Clone()

env_thirdparty.Prepend(CPPPATH=[thirdparty_dir + "include"])
env.Prepend(CPPPATH=[thirdparty_dir + "include"])

if env["platform"] == "windows" and not env["use_mingw"]:
    env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
    env.core_sources += thirdparty_obj

env.add_source_files(env.core_sources, "*.cpp")
